---
- name: Configure Proxmox no-subscription repos, custom networking, and prepare for Terraform
  hosts: proxmox
  gather_facts: true
  roles:
    - proxmox_repos
    - proxmox_custom_net
    - proxmox_terraform
