---
proxmox_custom_net_nic_name: "nic0"

# VLAN Definitions
proxmox_custom_net_vlan_trusted: 411
proxmox_custom_net_vlan_untrusted: 300

# Main Trusted Network
proxmox_custom_net_trusted_ip: "10.0.0.15/16"
proxmox_custom_net_trusted_gw: "10.0.0.1"

# Separated VM Network (IaC)
proxmox_custom_net_sep_ip: "10.0.101.1/16"

# dnsmasq Configuration
proxmox_custom_net_dnsmasq_domain: "pve.lol"
proxmox_custom_net_dnsmasq_range: "10.0.101.2,10.0.101.255,255.255.0.0,2h"
proxmox_custom_net_dnsmasq_router: "10.0.0.1"
proxmox_custom_net_dnsmasq_dns: "10.0.0.5" # upstream DNS
